robot:
  length: 0.22
  width: 0.156
  height: 0.09

wheels:
  radius: 0.035
  thickness: 0.039
  separation: 0.18

clearance:
  front: 0.25
  side: 0.18
  rear: 0.20

lidar:
  height: 0.0675
  offset_x: 0.0
  offset_y: 0.0

footprint:
  - [ 0.11,  0.078]
  - [ 0.11, -0.078]
  - [-0.11, -0.078]
  - [-0.11,  0.078]
